#!/usr/bin/env python3
"""Validate / check staleness of co-agent-generated AGENTS.md context.

co-agent distills CLAUDE.md ONCE into a lean, review-oriented AGENTS.md that Kiro,
Codex, and Agy all draw from — not a per-AI copy each:
  - AGENTS.md  → Codex CLI auto-loads it from the repo root (32 KiB project-doc cap;
                 merged git-root→cwd). Kiro's .kiro/steering/project-context.md
                 bridges to this SAME file via #[[file:AGENTS.md]] (not CLAUDE.md
                 directly — see ai-cli-adapters.md for the consistency rationale).
                 Agy also auto-loads AGENTS.md natively from its cwd (same convention
                 as Codex); the fan-out additionally folds it into Agy's context at
                 call time as defense-in-depth for non-root-cwd invocations.

Claude (the co-agent skill) writes AGENTS.md; this script does the mechanical checks:
staleness vs CLAUDE.md, size caps, the generated marker, and a secret scan. It is
NOT the distiller — distillation needs Claude.

Usage:
  python3 check_ai_context.py [project_dir]          # check (exit 1 if stale/oversized/missing)
  python3 check_ai_context.py [project_dir] --emit-marker   # print the marker line to embed when generating
  python3 check_ai_context.py [project_dir] --verify <file> # exit 0 ONLY if <file> is co-agent-generated,
                                                              # fresh vs CLAUDE.md, within cap, and secret-free —
                                                              # silent (no stdout), for scripted gates like the
                                                              # Agy fan-out fold-in (unlike the default mode, a
                                                              # MISSING or hand-written file is a fail here, not
                                                              # a note: "safe to hand to a third-party AI" must
                                                              # be a strict yes/no, not "nothing to report")

Marker (must be on/near line 1 of a generated file):
  <!-- generated-by: co-agent · source: CLAUDE.md · claude-md-sha: <sha12> · generated-at: <date> -->
"""
import sys
import os
import re
import hashlib
import datetime

MANAGED = {"AGENTS.md": 32 * 1024}  # filename → soft size cap (bytes)
# Not generated by co-agent — and co-agent no longer invokes the gemini CLI at all (Agy
# superseded it; ADR-010) — but a residual repo-root GEMINI.md an older co-agent version
# left is STILL auto-loaded by (a) any user-run `gemini` and (b) Agy's documented GEMINI.md
# back-compat path — and co-agent itself runs `agy` from the repo root in every advisory
# fan-out. We don't manage it, but if one is present we secret-scan it and suggest deletion.
RESIDUAL_SCAN = ("GEMINI.md",)
MARKER_RE = re.compile(r"generated-by:\s*co-agent")
SHA_RE = re.compile(r"claude-md-sha:\s*([0-9a-f]{12})")
SECRET_RE = re.compile(r"AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY|ghp_[A-Za-z0-9]{30,}|(?:password|secret|api[_-]?key)\s*[:=]\s*['\"][^'\"]{6,}", re.I)


def claude_sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]


def _file_problems(path, sha, cap=None):
    """Marker + freshness + (optional) size cap + secret checks for one generated file.
    Missing file or no marker both count as problems here — the caller decides whether
    that's a soft note (default report) or a hard fail (--verify)."""
    if not os.path.isfile(path):
        return ["missing"]
    with open(path, encoding="utf-8") as f:
        body = f.read()
    if not MARKER_RE.search(body):
        return ["hand-written (no co-agent marker)"]
    problems = []
    if cap is not None:
        size = len(body.encode("utf-8"))
        if size > cap:
            problems.append(f"{size} B > {cap} B cap — distill further (CLI will truncate)")
    m = SHA_RE.search(body)
    if not m:
        problems.append("missing claude-md-sha in marker — regenerate")
    elif m.group(1) != sha:
        problems.append("STALE — CLAUDE.md changed since generation (run /co-agent sync-context)")
    if SECRET_RE.search(body):
        problems.append("possible secret/credential in generated context — remove before sharing with external AIs")
    return problems


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    root = args[0] if args else "."
    emit = "--emit-marker" in sys.argv[1:]
    verify_idx = sys.argv.index("--verify") + 1 if "--verify" in sys.argv else None
    verify_target = sys.argv[verify_idx] if verify_idx and verify_idx < len(sys.argv) else None

    claude_path = os.path.join(root, "CLAUDE.md")
    if not os.path.isfile(claude_path):
        if verify_target:
            return 1   # no CLAUDE.md → nothing was distilled → not safe to hand out
        print(f"❌ no CLAUDE.md in {root} — nothing to sync from.")
        return 2
    with open(claude_path, encoding="utf-8") as f:
        src = f.read()
    sha = claude_sha(src)

    if emit:
        today = datetime.date.today().isoformat()
        print(f"<!-- generated-by: co-agent · source: CLAUDE.md · claude-md-sha: {sha} · "
              f"generated-at: {today} · DO NOT EDIT — edit CLAUDE.md then run /co-agent sync-context -->")
        return 0

    if verify_target:
        cap = MANAGED.get(verify_target)
        return 1 if _file_problems(os.path.join(root, verify_target), sha, cap) else 0

    problems, notes = [], []
    for name, cap in MANAGED.items():
        p = os.path.join(root, name)
        if not os.path.isfile(p):
            notes.append(f"{name}: not generated yet (run /co-agent sync-context)")
            continue
        with open(p, encoding="utf-8") as f:
            body = f.read()
        if not MARKER_RE.search(body):
            notes.append(f"{name}: hand-written (no co-agent marker) — leaving it alone")
            continue
        size = len(body.encode("utf-8"))
        if size > cap:
            problems.append(f"{name}: {size} B > {cap} B cap — distill further (CLI will truncate)")
        m = SHA_RE.search(body)
        if not m:
            problems.append(f"{name}: missing claude-md-sha in marker — regenerate")
        elif m.group(1) != sha:
            problems.append(f"{name}: STALE — CLAUDE.md changed since generation (run /co-agent sync-context)")
        if SECRET_RE.search(body):
            problems.append(f"{name}: possible secret/credential in generated context — remove before sharing with external AIs")

    # RESIDUAL_SCAN (unlike MANAGED) is secret-scanned only, never marker/staleness-checked:
    # co-agent never generated these files, so there's no CLAUDE.md-sha to compare against —
    # the only actionable risk on a residual file is a stale secret a third-party AI could load.
    for name in RESIDUAL_SCAN:
        p = os.path.join(root, name)
        if not os.path.isfile(p):
            continue
        with open(p, encoding="utf-8") as f:
            body = f.read()
        if SECRET_RE.search(body):
            problems.append(f"{name}: residual unmanaged file with a possible secret — "
                            f"delete it (co-agent no longer uses gemini, but Agy's GEMINI.md "
                            f"back-compat auto-load — which co-agent's own fan-out triggers "
                            f"from the repo root — or a user-run gemini CLI would ship it "
                            f"to a third-party AI)")
        else:
            notes.append(f"{name}: residual unmanaged file present (not generated) — consider deleting")

    for n in notes:
        print(f"   • {n}")
    if problems:
        print(f"❌ AI context files need attention ({len(problems)}):")
        for p in problems:
            print(f"   • {p}")
        return 1
    print("✅ AGENTS.md is in sync with CLAUDE.md, within size cap, no secrets.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
