import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { RemarpPreviewPanel } from './preview';
import { SlideOutlineProvider } from './outline';
import { RemarpCompletionProvider } from './completions';
import { execFile } from 'child_process';
import { CompiledPreviewRenderer } from './compiledPreview';
import { slideStarts } from './source';

const presentationFiles = ['_presentation.md', '_presentation.remarp.md', 'remarp.yaml', 'remarp.yml'];
let savingForBuild = false;
let buildQueue: Promise<unknown> = Promise.resolve();

/**
 * Check if an HTML document was generated by Remarp (has generator meta tag)
 */
export function isRemarpHtml(document: vscode.TextDocument): boolean {
    if (document.languageId !== 'html') { return false; }
    const head = document.getText().substring(0, 500);
    return head.includes('<meta name="generator" content="remarp">');
}

/**
 * Find the source .remarp.md file from a Remarp-generated HTML document
 */
export function findRemarpSource(document: vscode.TextDocument): string | null {
    const head = document.getText().substring(0, 1000);
    const match = head.match(/<meta name="remarp-source" content="([^"]+)">/);
    if (!match || !match[1]) { return null; }

    const sourceFileName = match[1];
    const htmlDir = path.dirname(document.fileName);

    // Search relative to HTML file location
    const searchPaths = [
        path.join(htmlDir, sourceFileName),
        path.join(htmlDir, '..', sourceFileName),
        path.join(htmlDir, '..', '..', sourceFileName),
    ];

    for (const p of searchPaths) {
        const resolved = path.resolve(p);
        if (fs.existsSync(resolved)) {
            return resolved;
        }
    }
    return null;
}

/**
 * Check if a document is a remarp file by looking for `remarp: true` in frontmatter
 * or checking if it has .remarp.md extension
 */
export function isRemarpDocument(document: vscode.TextDocument): boolean {
    // Check file extension first
    if (document.fileName.endsWith('.remarp.md') || path.basename(document.fileName) === '_presentation.md') {
        return true;
    }

    // Check for remarp: true in frontmatter
    const text = document.getText();
    const frontmatterMatch = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (frontmatterMatch) {
        const frontmatter = frontmatterMatch[1];
        // Check for remarp: true (with optional quotes)
        if (/^remarp:\s*(?:true|"true"|'true')\s*(?:#.*)?$/m.test(frontmatter)) {
            return true;
        }
    }

    return false;
}

/**
 * Set the language mode to remarp for markdown files with remarp: true
 */
async function setRemarpLanguageIfNeeded(document: vscode.TextDocument): Promise<void> {
    if (document.languageId === 'markdown' && isRemarpDocument(document)) {
        await vscode.languages.setTextDocumentLanguage(document, 'remarp');
    }
}

export function activate(context: vscode.ExtensionContext) {
    console.log('Remarp extension is now active');

    // Check all open markdown files for remarp: true
    vscode.workspace.textDocuments.forEach(doc => {
        setRemarpLanguageIfNeeded(doc);
    });

    // Watch for newly opened documents
    context.subscriptions.push(
        vscode.workspace.onDidOpenTextDocument((document) => {
            setRemarpLanguageIfNeeded(document);
        })
    );

    // Watch for document saves (in case remarp: true is added)
    context.subscriptions.push(
        vscode.workspace.onDidSaveTextDocument((document) => {
            setRemarpLanguageIfNeeded(document);
        })
    );

    // Register the preview panel command
    context.subscriptions.push(
        vscode.commands.registerCommand('remarp.preview', () => {
            const editor = vscode.window.activeTextEditor;
            if (editor && (editor.document.languageId === 'remarp' || isRemarpDocument(editor.document))) {
                RemarpPreviewPanel.createOrShow(context.extensionUri, editor.document);
            } else {
                vscode.window.showWarningMessage('Open a .remarp.md file to preview');
            }
        })
    );

    // Register the outline provider
    const outlineProvider = new SlideOutlineProvider();
    context.subscriptions.push(
        vscode.window.registerTreeDataProvider('remarpOutline', outlineProvider)
    );

    // Register completion provider
    const completionProvider = new RemarpCompletionProvider();
    context.subscriptions.push(
        vscode.languages.registerCompletionItemProvider(
            { language: 'remarp' },
            completionProvider,
            '@', ':', '='
        )
    );

    // Register slide navigation commands
    context.subscriptions.push(
        vscode.commands.registerCommand('remarp.nextSlide', () => {
            navigateSlide('next');
        })
    );

    context.subscriptions.push(
        vscode.commands.registerCommand('remarp.prevSlide', () => {
            navigateSlide('prev');
        })
    );

    // Output channel for build logs
    const buildOutput = vscode.window.createOutputChannel('Remarp Build');
    context.subscriptions.push(buildOutput);

    // Register build command
    context.subscriptions.push(
        vscode.commands.registerCommand('remarp.build', async () => {
            const editor = vscode.window.activeTextEditor;
            if (editor && (editor.document.languageId === 'remarp' || isRemarpDocument(editor.document))) {
                buildOutput.show(true);
                await buildRemarpFile(editor.document, buildOutput);
            } else {
                vscode.window.showWarningMessage('Open a .remarp.md file to build');
            }
        })
    );

    context.subscriptions.push(vscode.commands.registerCommand('remarp.previewCompiled', async () => {
        const document = vscode.window.activeTextEditor?.document;
        if (!document || !(document.languageId === 'remarp' || isRemarpDocument(document))) {
            vscode.window.showWarningMessage('Open Remarp source to build and preview.');
            return;
        }
        const htmlPath = await buildRemarpFile(document, buildOutput);
        if (!htmlPath) { return; }
        try {
            const html = fs.readFileSync(htmlPath, 'utf8');
            if (!vscode.workspace.isTrusted) { throw new Error('Compiled preview requires workspace trust.'); }
            const panel = vscode.window.createWebviewPanel('remarpCompiledPreview',
                `Remarp Compiled Preview - ${path.basename(htmlPath)}`, vscode.ViewColumn.Beside,
                { enableScripts: true, localResourceRoots: [vscode.Uri.file(path.dirname(document.fileName))] });
            panel.webview.html = new CompiledPreviewRenderer(panel, context.extensionUri).render({
                uri: vscode.Uri.file(htmlPath), getText: () => html
            });
        } catch (error) {
            buildOutput.show(true);
            vscode.window.showErrorMessage(`Remarp compiled preview failed: ${error}`);
        }
    }));

    // Submit issues to Claude Code
    context.subscriptions.push(
        vscode.commands.registerCommand('remarp.submitIssues', () => {
            const previewDoc = RemarpPreviewPanel.currentPanel?.document;
            const editor = vscode.window.activeTextEditor;
            const editorDoc = editor && (editor.document.languageId === 'remarp' || isRemarpDocument(editor.document)) ? editor.document : undefined;
            const targetDoc = previewDoc || editorDoc;
            if (targetDoc) {
                submitIssuesToClaude(targetDoc, buildOutput);
            } else {
                vscode.window.showWarningMessage('Open a .remarp.md file to submit issues');
            }
        })
    );

    // Auto-build on save
    context.subscriptions.push(
        vscode.workspace.onDidSaveTextDocument((document) => {
            if (!savingForBuild && vscode.workspace.isTrusted && (document.languageId === 'remarp' || isRemarpDocument(document))) {
                buildRemarpFile(document, buildOutput);
            }
        })
    );

    // Watch for document changes to update outline and preview
    context.subscriptions.push(
        vscode.workspace.onDidChangeTextDocument((event) => {
            if (event.document.languageId === 'remarp') {
                outlineProvider.refresh();
                RemarpPreviewPanel.update(event.document);
            }
        })
    );

    // Watch for active editor changes
    context.subscriptions.push(
        vscode.window.onDidChangeActiveTextEditor((editor) => {
            if (editor && editor.document.languageId === 'remarp') {
                outlineProvider.refresh();
            }
        })
    );

    // Watch for cursor position changes to sync with outline
    context.subscriptions.push(
        vscode.window.onDidChangeTextEditorSelection((event) => {
            if (event.textEditor.document.languageId === 'remarp') {
                const config = vscode.workspace.getConfiguration('remarp');
                if (config.get<boolean>('scrollSync', true)) {
                    RemarpPreviewPanel.syncCursor(event.textEditor);
                }
            }
        })
    );
}

function navigateSlide(direction: 'next' | 'prev'): void {
    const editor = vscode.window.activeTextEditor;
    if (!editor || editor.document.languageId !== 'remarp') {
        return;
    }

    const document = editor.document;
    const text = document.getText();
    const currentPosition = editor.selection.active;
    const currentOffset = document.offsetAt(currentPosition);

    const separators = slideStarts(text).map(line => document.offsetAt(new vscode.Position(line, 0)));

    if (separators.length === 0) {
        return;
    }

    let targetOffset: number | null = null;

    if (direction === 'next') {
        // Find the next separator after current position
        for (const sep of separators) {
            if (sep > currentOffset) {
                targetOffset = sep;
                break;
            }
        }
    } else {
        // Find the previous separator before current position
        for (let i = separators.length - 1; i >= 0; i--) {
            if (separators[i] < currentOffset - 1) {
                targetOffset = separators[i];
                break;
            }
        }
    }

    if (targetOffset !== null) {
        const targetPosition = document.positionAt(targetOffset);
        const newSelection = new vscode.Selection(targetPosition, targetPosition);
        editor.selection = newSelection;
        editor.revealRange(new vscode.Range(targetPosition, targetPosition), vscode.TextEditorRevealType.InCenter);
    }
}

/**
 * Recursively search for a script file inside a directory (max depth 5)
 */
function findScriptInDir(dir: string, scriptName: string, depth: number = 0): string | null {
    if (depth > 5) { return null; }
    try {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
            if (entry.isFile() && entry.name === scriptName) {
                return path.join(dir, entry.name);
            }
            if (entry.isDirectory() && !entry.name.startsWith('.')) {
                const found = findScriptInDir(path.join(dir, entry.name), scriptName, depth + 1);
                if (found) { return found; }
            }
        }
    } catch { /* permission errors, etc. */ }
    return null;
}

/**
 * Find remarp_to_slides.py script relative to the document
 */
function findBuildScript(document: vscode.TextDocument): string | null {
    const scriptName = 'remarp_to_slides.py';

    // 1. User-configured path (highest priority)
    const configPath = vscode.workspace.getConfiguration('remarp').get<string>('buildScriptPath', '');
    if (configPath && fs.existsSync(configPath)) {
        return configPath;
    }

    // 2. Search relative to the document directory
    const htmlDir = path.dirname(document.fileName);
    const searchPaths = [
        path.join(htmlDir, scriptName),
        path.join(htmlDir, 'scripts', scriptName),
        path.join(htmlDir, '..', 'scripts', scriptName),
    ];

    // 3. Workspace folders
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (workspaceFolders) {
        for (const folder of workspaceFolders) {
            searchPaths.push(path.join(folder.uri.fsPath, scriptName));
            searchPaths.push(path.join(folder.uri.fsPath, 'scripts', scriptName));
        }
    }

    for (const p of searchPaths) {
        const resolved = path.resolve(p);
        if (fs.existsSync(resolved)) {
            return resolved;
        }
    }

    // 3.5. Search inside plugin directories (plugins/**/scripts/)
    if (workspaceFolders) {
        for (const folder of workspaceFolders) {
            const pluginsDir = path.join(folder.uri.fsPath, 'plugins');
            if (fs.existsSync(pluginsDir)) {
                const found = findScriptInDir(pluginsDir, scriptName);
                if (found) { return found; }
            }
        }
    }

    // 4. Walk up from htmlDir toward root (max 5 levels)
    let current = htmlDir;
    for (let i = 0; i < 5; i++) {
        const parent = path.dirname(current);
        if (parent === current) { break; } // reached filesystem root
        for (const candidate of [path.join(parent, 'scripts', scriptName), path.join(parent, scriptName)]) {
            if (fs.existsSync(candidate)) {
                return candidate;
            }
        }
        current = parent;
    }

    return null;
}

/**
 * Build HTML from a remarp file
 */
function buildRemarpFile(document: vscode.TextDocument, outputChannel: vscode.OutputChannel): Promise<string | undefined> {
    const run = buildQueue.then(async () => {
        try {
            if (!vscode.workspace.isTrusted) { throw new Error('Building requires workspace trust.'); }
            if (document.uri.scheme !== 'file') { throw new Error('Save source to a local file before building.'); }
            const fileDir = path.dirname(document.fileName);
            const isProject = presentationFiles.some(name => fs.existsSync(path.join(fileDir, name))) ||
                presentationFiles.includes(path.basename(document.fileName));
            savingForBuild = true;
            try {
                const sources = new Set([document, ...vscode.workspace.textDocuments.filter(doc =>
                    isProject && path.dirname(doc.fileName) === fileDir && isRemarpDocument(doc))]);
                for (const source of sources) {
                    if (source.isDirty && !await source.save()) { throw new Error(`Could not save ${source.fileName}`); }
                }
            } finally { savingForBuild = false; }
            const outputs = await executeBuild(document, outputChannel, isProject ? fileDir : document.fileName);
            const preview = isProject ? path.join(fileDir, 'index.html') : outputs[0];
            if (!preview || !outputs.includes(preview)) { throw new Error('Compiler did not report a preview output.'); }
            return preview;
        } catch (error) {
            outputChannel.show(true);
            outputChannel.appendLine(`[Remarp Build] ${error}`);
            vscode.window.showErrorMessage(`Remarp build failed: ${error}`);
            return undefined;
        }
    });
    buildQueue = run;
    return run;
}

async function executeBuild(document: vscode.TextDocument, outputChannel: vscode.OutputChannel, target: string): Promise<string[]> {
    const scriptPath = findBuildScript(document);
    if (!scriptPath) {
        throw new Error('remarp_to_slides.py not found. Configure remarp.buildScriptPath.');
    }

    const filePath = document.fileName;
    const fileDir = path.dirname(filePath);

    const args = ['build', target];

    outputChannel.appendLine(`[Remarp Build] python3 ${scriptPath} ${args.join(' ')}`);

    return new Promise<string[]>((resolve, reject) => execFile('python3', [scriptPath, ...args], { cwd: fileDir }, (error, stdout, stderr) => {
        if (stdout) { outputChannel.appendLine(stdout); }
        if (stderr) { outputChannel.appendLine(stderr); }

        if (error) {
            outputChannel.appendLine(`[Remarp Build] Error: ${error.message}`);
            reject(error);
        } else {
            outputChannel.appendLine('[Remarp Build] Done');
            resolve(stdout.split(/\r?\n/).filter(line => line.startsWith('Generated: '))
                .map(line => path.resolve(fileDir, line.slice('Generated: '.length).trim())));
        }
    }));
}

/**
 * Show guidance to use /slide-fix skill in Claude Code
 */
function submitIssuesToClaude(document: vscode.TextDocument, outputChannel: vscode.OutputChannel): void {
    const issueCount = (document.getText().match(/<!--\s*issue:\s*.+?\s*-->/g) || []).length;
    if (issueCount === 0) {
        vscode.window.showInformationMessage('이슈 어노테이션이 없습니다.');
        return;
    }
    vscode.window.showInformationMessage(
        `${issueCount}개 이슈 발견. Claude Code에서 /slide-fix 실행하세요.`,
        'OK'
    );
}

export function deactivate() {
    // Cleanup
}
