import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { RemarpPreviewPanel } from './preview';
import { SlideOutlineProvider } from './outline';
import { RemarpCompletionProvider } from './completions';
import { execFile } from 'child_process';

/**
 * Check if an HTML document was generated by Remarp (has generator meta tag)
 */
export function isRemarpHtml(document: vscode.TextDocument): boolean {
    if (document.languageId !== 'html') { return false; }
    const head = document.getText().substring(0, 500);
    return head.includes('<meta name="generator" content="remarp">');
}

/**
 * Find the source .remarp.md file from a Remarp-generated HTML document
 */
export function findRemarpSource(document: vscode.TextDocument): string | null {
    const head = document.getText().substring(0, 1000);
    const match = head.match(/<meta name="remarp-source" content="([^"]+)">/);
    if (!match || !match[1]) { return null; }

    const sourceFileName = match[1];
    const htmlDir = path.dirname(document.fileName);

    // Search relative to HTML file location
    const searchPaths = [
        path.join(htmlDir, sourceFileName),
        path.join(htmlDir, '..', sourceFileName),
        path.join(htmlDir, '..', '..', sourceFileName),
    ];

    for (const p of searchPaths) {
        const resolved = path.resolve(p);
        if (fs.existsSync(resolved)) {
            return resolved;
        }
    }
    return null;
}

/**
 * Check if a document is a remarp file by looking for `remarp: true` in frontmatter
 * or checking if it has .remarp.md extension
 */
export function isRemarpDocument(document: vscode.TextDocument): boolean {
    // Check file extension first
    if (document.fileName.endsWith('.remarp.md')) {
        return true;
    }

    // Check for remarp: true in frontmatter
    const text = document.getText();
    const frontmatterMatch = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (frontmatterMatch) {
        const frontmatter = frontmatterMatch[1];
        // Check for remarp: true (with optional quotes)
        if (/^remarp:\s*(?:true|"true"|'true')\s*$/m.test(frontmatter)) {
            return true;
        }
    }

    return false;
}

/**
 * Set the language mode to remarp for markdown files with remarp: true
 */
async function setRemarpLanguageIfNeeded(document: vscode.TextDocument): Promise<void> {
    if (document.languageId === 'markdown' && isRemarpDocument(document)) {
        await vscode.languages.setTextDocumentLanguage(document, 'remarp');
    }
}

export function activate(context: vscode.ExtensionContext) {
    console.log('Remarp extension is now active');

    // Check all open markdown files for remarp: true
    vscode.workspace.textDocuments.forEach(doc => {
        setRemarpLanguageIfNeeded(doc);
    });

    // Helper: update remarp.isRemarpHtml context key for the active editor
    function updateRemarpHtmlContext(editor: vscode.TextEditor | undefined): void {
        const isHtml = editor ? isRemarpHtml(editor.document) : false;
        vscode.commands.executeCommand('setContext', 'remarp.isRemarpHtml', isHtml);
    }

    // Set initial context for already-open editor
    updateRemarpHtmlContext(vscode.window.activeTextEditor);

    // Watch for newly opened documents
    context.subscriptions.push(
        vscode.workspace.onDidOpenTextDocument((document) => {
            setRemarpLanguageIfNeeded(document);
        })
    );

    // Watch for document saves (in case remarp: true is added)
    context.subscriptions.push(
        vscode.workspace.onDidSaveTextDocument((document) => {
            setRemarpLanguageIfNeeded(document);
        })
    );

    // Register the preview panel command
    context.subscriptions.push(
        vscode.commands.registerCommand('remarp.preview', () => {
            const editor = vscode.window.activeTextEditor;
            if (editor && (editor.document.languageId === 'remarp' || isRemarpDocument(editor.document) || isRemarpHtml(editor.document))) {
                RemarpPreviewPanel.createOrShow(context.extensionUri, editor.document);
            } else {
                vscode.window.showWarningMessage('Open a .remarp.md file or a Remarp-generated HTML file to preview');
            }
        })
    );

    // Register the outline provider
    const outlineProvider = new SlideOutlineProvider();
    context.subscriptions.push(
        vscode.window.registerTreeDataProvider('remarpOutline', outlineProvider)
    );

    // Register completion provider
    const completionProvider = new RemarpCompletionProvider();
    context.subscriptions.push(
        vscode.languages.registerCompletionItemProvider(
            { language: 'remarp' },
            completionProvider,
            '@', ':', '='
        )
    );

    // Register slide navigation commands
    context.subscriptions.push(
        vscode.commands.registerCommand('remarp.nextSlide', () => {
            navigateSlide('next');
        })
    );

    context.subscriptions.push(
        vscode.commands.registerCommand('remarp.prevSlide', () => {
            navigateSlide('prev');
        })
    );

    // Output channel for build logs
    const buildOutput = vscode.window.createOutputChannel('Remarp Build');

    // Register build command
    context.subscriptions.push(
        vscode.commands.registerCommand('remarp.build', () => {
            const editor = vscode.window.activeTextEditor;
            if (editor && (editor.document.languageId === 'remarp' || isRemarpDocument(editor.document))) {
                buildOutput.show(true);
                buildRemarpFile(editor.document, buildOutput);
            } else if (editor && isRemarpHtml(editor.document)) {
                // For Remarp HTML, find and build the source file
                const sourcePath = findRemarpSource(editor.document);
                if (sourcePath) {
                    vscode.workspace.openTextDocument(sourcePath).then(sourceDoc => {
                        buildOutput.show(true);
                        buildRemarpFile(sourceDoc, buildOutput);
                    });
                } else {
                    vscode.window.showWarningMessage('Could not find source .remarp.md for this HTML file');
                }
            } else {
                vscode.window.showWarningMessage('Open a .remarp.md file or Remarp HTML to build');
            }
        })
    );

    // Submit issues to Claude Code
    context.subscriptions.push(
        vscode.commands.registerCommand('remarp.submitIssues', () => {
            const previewDoc = RemarpPreviewPanel.currentPanel?.document;
            const editor = vscode.window.activeTextEditor;
            const editorDoc = editor && (editor.document.languageId === 'remarp' || isRemarpDocument(editor.document)) ? editor.document : undefined;
            const targetDoc = previewDoc || editorDoc;
            if (targetDoc) {
                submitIssuesToClaude(targetDoc, buildOutput);
            } else {
                vscode.window.showWarningMessage('Open a .remarp.md file to submit issues');
            }
        })
    );

    // Auto-build on save
    context.subscriptions.push(
        vscode.workspace.onDidSaveTextDocument((document) => {
            if (document.languageId === 'remarp' || isRemarpDocument(document)) {
                buildRemarpFile(document, buildOutput);
            }
        })
    );

    // Watch for document changes to update outline and preview
    context.subscriptions.push(
        vscode.workspace.onDidChangeTextDocument((event) => {
            if (event.document.languageId === 'remarp') {
                outlineProvider.refresh();
                RemarpPreviewPanel.update(event.document);
            }
        })
    );

    // Watch for active editor changes
    context.subscriptions.push(
        vscode.window.onDidChangeActiveTextEditor((editor) => {
            updateRemarpHtmlContext(editor);
            if (editor && editor.document.languageId === 'remarp') {
                outlineProvider.refresh();
            }
        })
    );

    // Watch for cursor position changes to sync with outline
    context.subscriptions.push(
        vscode.window.onDidChangeTextEditorSelection((event) => {
            if (event.textEditor.document.languageId === 'remarp') {
                const config = vscode.workspace.getConfiguration('remarp');
                if (config.get<boolean>('scrollSync', true)) {
                    RemarpPreviewPanel.syncCursor(event.textEditor);
                }
            }
        })
    );
}

function navigateSlide(direction: 'next' | 'prev'): void {
    const editor = vscode.window.activeTextEditor;
    if (!editor || editor.document.languageId !== 'remarp') {
        return;
    }

    const document = editor.document;
    const text = document.getText();
    const currentPosition = editor.selection.active;
    const currentOffset = document.offsetAt(currentPosition);

    // Find all slide separators (---)
    const separatorRegex = /^---$/gm;
    const separators: number[] = [];
    let match;

    while ((match = separatorRegex.exec(text)) !== null) {
        separators.push(match.index);
    }

    if (separators.length === 0) {
        return;
    }

    let targetOffset: number | null = null;

    if (direction === 'next') {
        // Find the next separator after current position
        for (const sep of separators) {
            if (sep > currentOffset) {
                targetOffset = sep;
                break;
            }
        }
    } else {
        // Find the previous separator before current position
        for (let i = separators.length - 1; i >= 0; i--) {
            if (separators[i] < currentOffset - 1) {
                targetOffset = separators[i];
                break;
            }
        }
    }

    if (targetOffset !== null) {
        const targetPosition = document.positionAt(targetOffset);
        const newSelection = new vscode.Selection(targetPosition, targetPosition);
        editor.selection = newSelection;
        editor.revealRange(new vscode.Range(targetPosition, targetPosition), vscode.TextEditorRevealType.InCenter);
    }
}

/**
 * Recursively search for a script file inside a directory (max depth 5)
 */
function findScriptInDir(dir: string, scriptName: string, depth: number = 0): string | null {
    if (depth > 5) { return null; }
    try {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
            if (entry.isFile() && entry.name === scriptName) {
                return path.join(dir, entry.name);
            }
            if (entry.isDirectory() && !entry.name.startsWith('.')) {
                const found = findScriptInDir(path.join(dir, entry.name), scriptName, depth + 1);
                if (found) { return found; }
            }
        }
    } catch { /* permission errors, etc. */ }
    return null;
}

/**
 * Find remarp_to_slides.py script relative to the document
 */
function findBuildScript(document: vscode.TextDocument): string | null {
    const scriptName = 'remarp_to_slides.py';

    // 1. User-configured path (highest priority)
    const configPath = vscode.workspace.getConfiguration('remarp').get<string>('buildScriptPath', '');
    if (configPath && fs.existsSync(configPath)) {
        return configPath;
    }

    // 2. Search relative to the document directory
    const htmlDir = path.dirname(document.fileName);
    const searchPaths = [
        path.join(htmlDir, scriptName),
        path.join(htmlDir, 'scripts', scriptName),
        path.join(htmlDir, '..', 'scripts', scriptName),
    ];

    // 3. Workspace folders
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (workspaceFolders) {
        for (const folder of workspaceFolders) {
            searchPaths.push(path.join(folder.uri.fsPath, scriptName));
            searchPaths.push(path.join(folder.uri.fsPath, 'scripts', scriptName));
        }
    }

    for (const p of searchPaths) {
        const resolved = path.resolve(p);
        if (fs.existsSync(resolved)) {
            return resolved;
        }
    }

    // 3.5. Search inside plugin directories (plugins/**/scripts/)
    if (workspaceFolders) {
        for (const folder of workspaceFolders) {
            const pluginsDir = path.join(folder.uri.fsPath, 'plugins');
            if (fs.existsSync(pluginsDir)) {
                const found = findScriptInDir(pluginsDir, scriptName);
                if (found) { return found; }
            }
        }
    }

    // 4. Walk up from htmlDir toward root (max 5 levels)
    let current = htmlDir;
    for (let i = 0; i < 5; i++) {
        const parent = path.dirname(current);
        if (parent === current) { break; } // reached filesystem root
        for (const candidate of [path.join(parent, 'scripts', scriptName), path.join(parent, scriptName)]) {
            if (fs.existsSync(candidate)) {
                return candidate;
            }
        }
        current = parent;
    }

    return null;
}

/**
 * Build HTML from a remarp file
 */
function buildRemarpFile(document: vscode.TextDocument, outputChannel: vscode.OutputChannel): void {
    const scriptPath = findBuildScript(document);
    if (!scriptPath) {
        vscode.window.showWarningMessage('remarp_to_slides.py not found. Cannot build HTML.');
        return;
    }

    const filePath = document.fileName;
    const fileDir = path.dirname(filePath);

    // Check if this is a project directory (has multiple .remarp.md or block files)
    const isProject = fs.existsSync(path.join(fileDir, 'remarp.yaml')) ||
                      fs.existsSync(path.join(fileDir, 'remarp.yml'));

    const args = isProject
        ? ['sync', fileDir]
        : ['build', filePath];

    outputChannel.appendLine(`[Remarp Build] python3 ${scriptPath} ${args.join(' ')}`);

    execFile('python3', [scriptPath, ...args], { cwd: fileDir }, (error, stdout, stderr) => {
        if (stdout) { outputChannel.appendLine(stdout); }
        if (stderr) { outputChannel.appendLine(stderr); }

        if (error) {
            outputChannel.appendLine(`[Remarp Build] Error: ${error.message}`);
            vscode.window.showErrorMessage(`Remarp build failed: ${error.message}`);
        } else {
            outputChannel.appendLine('[Remarp Build] Done');
        }
    });
}

/**
 * Submit all issue annotations to Claude Code CLI for auto-fix
 */
/**
 * Find claude CLI binary path
 */
function findClaudeCli(): string | null {
    const homeDir = process.env.HOME || process.env.USERPROFILE || '';
    const candidates = [
        path.join(homeDir, '.local', 'bin', 'claude'),
        '/usr/local/bin/claude',
        'claude', // fallback to PATH
    ];
    for (const candidate of candidates) {
        if (candidate === 'claude' || fs.existsSync(candidate)) {
            return candidate;
        }
    }
    return null;
}

function submitIssuesToClaude(document: vscode.TextDocument, outputChannel: vscode.OutputChannel): void {
    const scriptPath = findBuildScript(document);
    if (!scriptPath) {
        vscode.window.showWarningMessage('remarp_to_slides.py not found. Cannot collect issues.');
        return;
    }

    const claudePath = findClaudeCli();
    if (!claudePath) {
        vscode.window.showErrorMessage('Claude CLI not found. Install with: npm install -g @anthropic-ai/claude-code');
        return;
    }

    const filePath = document.fileName;
    const fileDir = path.dirname(filePath);

    outputChannel.show(true);
    outputChannel.appendLine(`[Remarp Issues] Collecting issues from ${filePath}...`);

    // Step 1: Collect issues via remarp_to_slides.py issues --json
    execFile('python3', [scriptPath, 'issues', filePath, '--json'], { cwd: fileDir }, (error, stdout, stderr) => {
        if (stderr) { outputChannel.appendLine(stderr); }
        if (error) {
            outputChannel.appendLine(`[Remarp Issues] Error: ${error.message}`);
            vscode.window.showErrorMessage(`Failed to collect issues: ${error.message}`);
            return;
        }

        let issues: Array<{ file: string; block: string; slide: number; title: string; issue: string }>;
        try {
            issues = JSON.parse(stdout);
        } catch {
            vscode.window.showInformationMessage('No issues found in this file.');
            return;
        }

        if (!issues || issues.length === 0) {
            vscode.window.showInformationMessage('No issues found in this file.');
            return;
        }

        // Step 2: Build prompt
        const issueList = issues.map(i => `- Slide ${i.slide} "${i.title}": ${i.issue}`).join('\n');
        const prompt = [
            `다음 Remarp 마크다운 파일의 슬라이드 이슈들을 수정해주세요.`,
            `파일: ${filePath}`,
            ``,
            `이슈 목록:`,
            issueList,
            ``,
            `각 이슈를 읽고 해당 슬라이드의 마크다운 내용을 직접 수정하세요.`,
            `수정 완료 후 해당 <!-- !issue: ... --> 주석을 제거하세요.`,
        ].join('\n');

        outputChannel.appendLine(`[Remarp Issues] Submitting ${issues.length} issue(s) to Claude...`);
        outputChannel.appendLine(`[Remarp Issues] Claude CLI: ${claudePath}`);
        outputChannel.appendLine(`[Remarp Issues] Prompt:\n${prompt}\n`);

        // Step 3: Execute Claude CLI with progress
        vscode.window.withProgress(
            {
                location: vscode.ProgressLocation.Notification,
                title: `Remarp: Claude가 ${issues.length}개 이슈를 처리 중...`,
                cancellable: false,
            },
            () => {
                return new Promise<void>((resolve) => {
                    const env = { ...process.env };
                    // Ensure ~/.local/bin is in PATH
                    const homeDir = process.env.HOME || '';
                    if (homeDir) {
                        env.PATH = `${path.join(homeDir, '.local', 'bin')}:${env.PATH || ''}`;
                    }

                    execFile(
                        claudePath,
                        [
                            '--print',
                            '--allowedTools', 'Read,Edit,Glob,Grep',
                            '--max-budget-usd', '1.00',
                            '-p', prompt,
                        ],
                        { cwd: fileDir, timeout: 300000, env, maxBuffer: 10 * 1024 * 1024 },
                        (err, cliStdout, cliStderr) => {
                            if (cliStdout) { outputChannel.appendLine(cliStdout); }
                            if (cliStderr) { outputChannel.appendLine(cliStderr); }

                            if (err) {
                                outputChannel.appendLine(`[Remarp Issues] Claude error: ${err.message}`);
                                vscode.window.showErrorMessage(`Claude issue fix failed: ${err.message}`);
                            } else {
                                outputChannel.appendLine('[Remarp Issues] Claude completed successfully');
                                vscode.window.showInformationMessage(
                                    `${issues.length}개 이슈 처리 완료. 슬라이드를 확인하세요.`
                                );
                                // Refresh preview
                                RemarpPreviewPanel.update(document);
                            }
                            resolve();
                        }
                    );
                });
            }
        );
    });
}

export function deactivate() {
    // Cleanup
}
