#!/usr/bin/env python3
"""Generate Codex entry points from shared skills, commands and agent procedures."""
from __future__ import annotations

import argparse
from collections import defaultdict
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED = {"README.md", "CLAUDE.md", "AGENTS.md"}
# Codex 0.154 also migrates these argument-free source commands automatically.
# Reuse its stable names so the explicit, host-adapted skill wins deduplication.
COMMAND_ALIASES = {
    ("atlas", "graph"): "source-command-graph",
    ("project-init", "health-check"): "source-command-health-check",
}


def dump(value):
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def frontmatter(path):
    text = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\r?\n(.*?)\r?\n---(?:\r?\n|$)", text, re.S)
    if not match:
        raise ValueError(f"{path}: missing frontmatter")
    result = {}
    for key in ("name", "description", "disable-model-invocation"):
        field = re.search(rf"^{key}:\s*(.+)$", match[1], re.M)
        if field:
            value = field[1].strip()
            if value.startswith('"'):
                value = json.loads(value)
            elif value.startswith("'") and value.endswith("'"):
                value = value[1:-1].replace("''", "'")
            if value in ("|", ">"):
                raise ValueError(f"{path}: unsupported multiline {key}; extend parser")
            result[key] = value
    if not result.get("description"):
        raise ValueError(f"{path}: missing description")
    return result


def generated_files(root):
    # Template content is data. --root never imports or executes code from that
    # tree, so trusted validation can inspect a different checkout safely.
    templates = root / "scripts/codex"
    interfaces = json.loads((templates / "interfaces.json").read_text(encoding="utf-8"))
    outputs = {}
    for manifest_path in sorted((root / "plugins").glob("*/.claude-plugin/plugin.json")):
        plugin = manifest_path.parents[1]
        name = plugin.name
        source_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        adapter = plugin / ".codex-plugin"
        groups = defaultdict(list)
        for pattern in ("skills/*/SKILL.md", "commands/*.md", "agents/*.md"):
            for source in sorted(plugin.glob(pattern)):
                if source.name in EXCLUDED:
                    continue
                meta = frontmatter(source)
                skill_name = meta.get("name") or source.stem
                if source.parent.name == "commands":
                    skill_name = COMMAND_ALIASES.get((name, source.stem), skill_name)
                if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", skill_name):
                    raise ValueError(f"{source}: invalid skill name {skill_name!r}")
                groups[skill_name].append((source, meta))
        inventory = {"plugin": name, "skills": []}
        for skill_name, sources in sorted(groups.items()):
            # Skills are visited before commands: a command that is just an alias
            # augments the existing skill instead of becoming a duplicate.
            description = sources[0][1]["description"]
            if name == "project-init":
                description = description.replace("Claude Code", "Codex or Claude Code")
            path = adapter / "skills" / skill_name / "SKILL.md"
            source_paths = [str(s.relative_to(plugin)) for s, _ in sources]
            inventory["skills"].append({
                "name": skill_name, "path": str(path.relative_to(plugin)),
                "sources": source_paths,
            })
            body = (
                f"---\nname: {skill_name}\ndescription: {json.dumps(description, ensure_ascii=False)}\n---\n\n"
                "<!-- Generated by scripts/sync-codex-plugins.py; edit the shared source. -->\n\n"
                f"# {skill_name}\n\n"
                "Read [Codex runtime guidance](../../runtime.md) first, then the "
                "relevant shared procedure below. Keep references relative to that source.\n\n"
            )
            if (templates / f"{name}.md").is_file():
                body += "Apply [this plugin's Codex workflow](../../workflow.md).\n\n"
            for source_path in source_paths:
                body += f"- [{source_path}](../../../{source_path})\n"
            outputs[path] = body
            if any(meta.get("disable-model-invocation") == "true" for _, meta in sources):
                outputs[path.parent / "agents/openai.yaml"] = (
                    "policy:\n  allow_implicit_invocation: false\n"
                )
        outputs[adapter / "inventory.json"] = dump(inventory)
        outputs[adapter / "runtime.md"] = (templates / "runtime.md").read_text(encoding="utf-8")
        outputs[adapter / "run.py"] = (templates / "run.py").read_text(encoding="utf-8")
        if (templates / f"{name}.md").is_file():
            outputs[adapter / "workflow.md"] = (templates / f"{name}.md").read_text(encoding="utf-8")
        manifest = {
            key: source_manifest[key]
            for key in ("name", "version", "description", "author", "homepage", "repository", "license", "keywords")
            if key in source_manifest
        }
        manifest["skills"] = "./.codex-plugin/skills/"
        manifest["interface"] = interfaces[name]
        mcp = source_manifest.get("mcpServers")
        if mcp:
            if isinstance(mcp, str):
                mcp = json.loads((plugin / mcp).read_text(encoding="utf-8"))
            elif isinstance(mcp, dict) and "mcpServers" not in mcp:
                mcp = {"mcpServers": mcp}
            outputs[adapter / "mcp.json"] = dump(mcp)
            manifest["mcpServers"] = "./.codex-plugin/mcp.json"
        hooks = source_manifest.get("hooks")
        if hooks:
            if isinstance(hooks, str):
                hooks = json.loads((plugin / hooks).read_text(encoding="utf-8"))["hooks"]
            handlers = []
            codex_hooks = {}
            for event, groups_for_event in hooks.items():
                codex_groups = []
                for group in groups_for_event:
                    adapted = []
                    for handler in group["hooks"]:
                        if handler.get("type") != "command":
                            raise ValueError(f"{name}: {event} hook needs an explicit Codex adaptation")
                        index = len(handlers)
                        handlers.append({
                            "event": event, "matcher": group.get("matcher", ""),
                            "command": handler["command"],
                        })
                        adapted.append({
                            **handler,
                            "command": f'python3 "${{PLUGIN_ROOT}}/.codex-plugin/hook.py" {index}',
                        })
                    codex_groups.append({**group, "hooks": adapted})
                codex_hooks[event] = codex_groups
            outputs[adapter / "hooks.json"] = dump({"hooks": codex_hooks})
            outputs[adapter / "hook-handlers.json"] = dump({"plugin": name, "handlers": handlers})
            outputs[adapter / "hook.py"] = (templates / "hook.py").read_text(encoding="utf-8")
            manifest["hooks"] = "./.codex-plugin/hooks.json"
        outputs[adapter / "plugin.json"] = dump(manifest)
    marketplace_path = root / ".agents/plugins/marketplace.json"
    marketplace = json.loads(marketplace_path.read_text(encoding="utf-8"))
    existing = {entry["name"] for entry in marketplace["plugins"]}
    for plugin in sorted(interfaces):
        if plugin not in existing:
            source = root / "plugins" / plugin / ".claude-plugin/plugin.json"
            version = json.loads(source.read_text(encoding="utf-8"))["version"]
            marketplace["plugins"].append({
                "name": plugin,
                "source": {"source": "local", "path": f"./plugins/{plugin}"},
                "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
                "category": interfaces[plugin]["category"], "version": version,
            })
    outputs[marketplace_path] = dump(marketplace)
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    args.root = args.root.resolve()
    try:
        outputs = generated_files(args.root)
    except (OSError, ValueError, KeyError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    stale = []
    for path, content in outputs.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    # Only remove files in the explicitly generated skills tree, never arbitrary
    # user or source files under the plugin.
    for plugin in (args.root / "plugins").iterdir():
        skills_root = plugin / ".codex-plugin/skills"
        for path in skills_root.rglob("*"):
            if path.is_file() and path not in outputs:
                stale.append(path)
                if not args.check:
                    path.unlink()
        for path in sorted(skills_root.rglob("*"), key=lambda p: len(p.parts), reverse=True):
            if path.is_dir() and not any(path.iterdir()):
                stale.append(path)
                if not args.check:
                    path.rmdir()
    if args.check and stale:
        for path in stale:
            print(f"stale Codex artifact: {path.relative_to(args.root)}")
        return 1
    print(f"Codex artifacts {'checked' if args.check else 'generated'}: {len(outputs)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
