#!/usr/bin/env python3
"""Generate Codex entry points from shared skills, commands and agent procedures."""
from __future__ import annotations

import argparse
from collections import defaultdict
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED = {"README.md", "CLAUDE.md", "AGENTS.md"}
OPTIONAL_ARTIFACTS = ("hook.py", "hooks.json", "hook-handlers.json", "mcp.json", "workflow.md")
# Codex 0.154 also migrates these argument-free source commands automatically.
# Reuse its stable names so the explicit, host-adapted skill wins deduplication.
COMMAND_ALIASES = {
    ("atlas", "graph"): "source-command-graph",
    ("project-init", "health-check"): "source-command-health-check",
}
# Keep the public command alias, but let its canonical skill own automatic routing.
EXPLICIT_COMMANDS = {("kiro", "delegate")}


def dump(value):
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def frontmatter(path):
    text = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\r?\n(.*?)\r?\n---(?:\r?\n|$)", text, re.S)
    if not match:
        raise ValueError(f"{path}: missing frontmatter")
    result = {}
    for key in ("name", "description", "disable-model-invocation"):
        field = re.search(rf"^{key}:\s*(.+)$", match[1], re.M)
        if field:
            value = field[1].strip()
            if value.startswith('"'):
                value = json.loads(value)
            elif value.startswith("'") and value.endswith("'"):
                value = value[1:-1].replace("''", "'")
            if value in ("|", ">"):
                raise ValueError(f"{path}: unsupported multiline {key}; extend parser")
            result[key] = value
    if not result.get("description"):
        raise ValueError(f"{path}: missing description")
    return result


def generated_files(root, plugins=None):
    # Template content is data. --root never imports or executes code from that
    # tree, so trusted validation can inspect a different checkout safely.
    templates = root / "scripts/codex"
    interfaces = json.loads((templates / "interfaces.json").read_text(encoding="utf-8"))
    outputs = {}
    manifests = sorted((root / "plugins").glob("*/.claude-plugin/plugin.json"))
    known = {path.parents[1].name for path in manifests}
    if plugins and plugins - known:
        raise ValueError(f"Unknown plugins: {', '.join(sorted(plugins - known))}")
    selected = known if plugins is None else plugins
    for manifest_path in manifests:
        plugin = manifest_path.parents[1]
        name = plugin.name
        if name not in selected:
            continue
        source_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        adapter = plugin / ".codex-plugin"
        groups = defaultdict(list)
        for pattern in ("skills/*/SKILL.md", "commands/*.md", "agents/*.md"):
            for source in sorted(plugin.glob(pattern)):
                if source.name in EXCLUDED:
                    continue
                meta = frontmatter(source)
                skill_name = meta.get("name") or source.stem
                if source.parent.name == "commands":
                    skill_name = COMMAND_ALIASES.get((name, source.stem), skill_name)
                if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", skill_name):
                    raise ValueError(f"{source}: invalid skill name {skill_name!r}")
                groups[skill_name].append((source, meta))
        inventory = {"plugin": name, "skills": []}
        for skill_name, sources in sorted(groups.items()):
            # Skills are visited before commands: a command that is just an alias
            # augments the existing skill instead of becoming a duplicate.
            description = sources[0][1]["description"]
            if name == "project-init":
                description = description.replace("Claude Code", "Codex or Claude Code")
            path = adapter / "skills" / skill_name / "SKILL.md"
            source_paths = [str(s.relative_to(plugin)) for s, _ in sources]
            inventory["skills"].append({
                "name": skill_name, "path": str(path.relative_to(plugin)),
                "sources": source_paths,
            })
            body = (
                f"---\nname: {skill_name}\ndescription: {json.dumps(description, ensure_ascii=False)}\n---\n\n"
                "<!-- Generated by scripts/sync-codex-plugins.py; edit the shared source. -->\n\n"
                f"# {skill_name}\n\n"
                "Read [Codex runtime guidance](../../runtime.md) first, then the "
                "relevant shared procedure below. Keep references relative to that source.\n\n"
            )
            if (templates / f"{name}.md").is_file():
                body += "Apply [this plugin's Codex workflow](../../workflow.md).\n\n"
            for source_path in source_paths:
                body += f"- [{source_path}](../../../{source_path})\n"
            outputs[path] = body
            worker_only = all(source.parent.name == "agents" for source, _ in sources)
            if (worker_only or (name, skill_name) in EXPLICIT_COMMANDS
                    or any(meta.get("disable-model-invocation") == "true" for _, meta in sources)):
                outputs[path.parent / "agents/openai.yaml"] = (
                    "policy:\n  allow_implicit_invocation: false\n"
                )
        outputs[adapter / "inventory.json"] = dump(inventory)
        outputs[adapter / "runtime.md"] = (templates / "runtime.md").read_text(encoding="utf-8")
        outputs[adapter / "run.py"] = (templates / "run.py").read_text(encoding="utf-8")
        if (templates / f"{name}.md").is_file():
            outputs[adapter / "workflow.md"] = (templates / f"{name}.md").read_text(encoding="utf-8")
        project_template = templates / f"{name}-project"
        if project_template.is_dir():
            for source in project_template.rglob("*"):
                if source.is_file() and "__pycache__" not in source.parts:
                    outputs[adapter / "project-template" / source.relative_to(project_template)] = (
                        source.read_text(encoding="utf-8")
                    )
        manifest = {
            key: source_manifest[key]
            for key in ("name", "version", "description", "author", "homepage", "repository", "license", "keywords")
            if key in source_manifest
        }
        manifest["skills"] = "./.codex-plugin/skills/"
        manifest["interface"] = interfaces[name]
        mcp = source_manifest.get("mcpServers")
        if mcp:
            if isinstance(mcp, str):
                mcp = json.loads((plugin / mcp).read_text(encoding="utf-8"))
            elif isinstance(mcp, dict) and "mcpServers" not in mcp:
                mcp = {"mcpServers": mcp}
            outputs[adapter / "mcp.json"] = dump(mcp)
            manifest["mcpServers"] = "./.codex-plugin/mcp.json"
        hooks = source_manifest.get("hooks")
        if hooks:
            if isinstance(hooks, str):
                hooks = json.loads((plugin / hooks).read_text(encoding="utf-8"))["hooks"]
            handlers = []
            codex_hooks = {}
            for event, groups_for_event in hooks.items():
                codex_groups = []
                for group in groups_for_event:
                    adapted = []
                    for handler in group["hooks"]:
                        if handler.get("type") != "command":
                            raise ValueError(f"{name}: {event} hook needs an explicit Codex adaptation")
                        index = len(handlers)
                        handlers.append({
                            "event": event, "matcher": group.get("matcher", ""),
                            "command": handler["command"],
                        })
                        adapted.append({
                            **handler,
                            "command": f'python3 "${{PLUGIN_ROOT}}/.codex-plugin/hook.py" {index}',
                        })
                    adapted_group = {**group, "hooks": adapted}
                    matcher = group.get("matcher", "")
                    if event in {"PreToolUse", "PostToolUse"} and matcher not in ("", "*") and any(
                        re.search(matcher, alias) for alias in ("Edit", "Write")
                    ):
                        # Codex aliases Edit/Write today; name apply_patch
                        # explicitly as well. The bridge retains the original
                        # matcher and filters by Add/Update/Delete operation.
                        adapted_group["matcher"] = f"(?:{matcher})|^apply_patch$"
                    codex_groups.append(adapted_group)
                codex_hooks[event] = codex_groups
            outputs[adapter / "hooks.json"] = dump({"hooks": codex_hooks})
            outputs[adapter / "hook-handlers.json"] = dump({"plugin": name, "handlers": handlers})
            outputs[adapter / "hook.py"] = (templates / "hook.py").read_text(encoding="utf-8")
            manifest["hooks"] = "./.codex-plugin/hooks.json"
        outputs[adapter / "plugin.json"] = dump(manifest)
    marketplace_path = root / ".agents/plugins/marketplace.json"
    marketplace = json.loads(marketplace_path.read_text(encoding="utf-8"))
    existing = {entry["name"]: entry for entry in marketplace["plugins"]}
    for plugin in sorted(selected):
        source = root / "plugins" / plugin / ".claude-plugin/plugin.json"
        version = json.loads(source.read_text(encoding="utf-8"))["version"]
        if plugin not in existing:
            marketplace["plugins"].append({
                "name": plugin,
                "source": {"source": "local", "path": f"./plugins/{plugin}"},
                "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
                "category": interfaces[plugin]["category"], "version": version,
            })
        else:
            existing[plugin]["version"] = version
    outputs[marketplace_path] = dump(marketplace)
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--plugin", action="append", help="Generate/check one plugin; repeat to select several")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    args.root = args.root.resolve()
    selected = set(args.plugin) if args.plugin else None
    try:
        outputs = generated_files(args.root, selected)
    except (OSError, ValueError, KeyError, re.error) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    stale = []
    for path, content in outputs.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    # Prune only reserved generated paths; preserve arbitrary operator/source files.
    for plugin in (args.root / "plugins").iterdir():
        if not (plugin / ".claude-plugin/plugin.json").is_file():
            continue
        if selected is not None and plugin.name not in selected:
            continue
        for name in OPTIONAL_ARTIFACTS:
            path = plugin / ".codex-plugin" / name
            if path not in outputs and (path.is_file() or path.is_symlink()):
                stale.append(path)
                if not args.check:
                    path.unlink()
        for tree in ("skills", "project-template"):
            generated_root = plugin / ".codex-plugin" / tree
            for path in generated_root.rglob("*"):
                if path.is_file() and path not in outputs:
                    stale.append(path)
                    if not args.check:
                        path.unlink()
            for path in sorted(generated_root.rglob("*"), key=lambda p: len(p.parts), reverse=True):
                if path.is_dir() and not any(path.iterdir()):
                    stale.append(path)
                    if not args.check:
                        path.rmdir()
    if args.check and stale:
        for path in stale:
            print(f"stale Codex artifact: {path.relative_to(args.root)}")
        return 1
    scope = ", ".join(sorted(selected)) if selected is not None else "all plugins"
    print(f"Codex artifacts {'checked' if args.check else 'generated'}: {len(outputs)} files ({scope})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
